# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["p.shanmugam832@mybvc.ca"]
description = "Fetch static game assets from GitHub via Fastly CDN"
language = "javascript"
manifest_version = 3
name = "github-game-cdn"
service_id = ""
